### ISSUE TITLE
more functions with sinatra

### ISSUE THREAD

**Issue by devvit** [jaredbeck/paper_trail-sinatra#4]
Sir, as I saw, ```paper_trail``` now use ```request_store``` for context storage completely,

currently, ```paper_trail-sinatra``` only contains ```whodunnit```,

I can add a few lines simply to get more functions:
```ruby
#line 35
::PaperTrail.whodunnit = user_for_paper_trail if ::PaperTrail.enabled?
PaperTrail.enabled_for_controller = paper_trail_enabled_for_controller
PaperTrail.controller_info = info_for_paper_trail
```

Is it correct? ```request_store``` is thread-safe for rack app

thanks :)

**Comment by jaredbeck** [comment]
Hi @devvit I'd be happy to review two separate PR: one for `controller_info` and one for `enabled_for_controller`. Each PR should include documentation and tests. Thanks!

**Comment by devvit** [comment]
closed, PR created
